dependencies:
- name: elasticsearch
  version: "7.2.0"
  repository: "file://../elasticsearch"
  condition: elasticsearch.enabled
- name: kibana
  version: "7.2.0"
  repository: "file://../kibana"
  condition: kibana.enabled
- name: logstash
  version: "7.2.0"
  repository: "file://../logstash"
  condition: logstash.enabled
- name: filebeat
  version: "7.2.0"
  repository: "file://../filebeat"
  condition: filebeat.enabled
- name: fluentd
  version: "4.3.2"
  repository: "file://../fluentd"
  condition: fluentd.enabled