---
elasticsearch:
    enabled: true
    clusterName: "elastic-cluster"
    nodeGroup: "master"
    replicas: 2 #Number of Elastic nodes you want
 
kibana:
    enabled: true
    elasticsearchHosts: "http://elastic-cluster-master:9200"
     
filebeat:
    enabled: true
    extraEnvs:
    - name: ELASTICSEARCH_HOSTS
      value: "http://elastic-cluster-master:9200"
 
logstash:
    enabled: false
 
fluentd:
    enabled: false